version: '3.9'

services:
  db:
    image: postgres:14.0-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: pass123
  test-db:
    image: postgres:14.0-alpine
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: pass123
